**Program**: 2_PISA data by country<br>
**Group**: Spring 2025, Data Mining, Final Project, Group 11<br>
**Group Members**: Sean Fitzgerald, Nick Mobus, Vanessa Thorsten<br>
**Description**: This program merges the following datafiles into an analysis file:<br>
- PISA country codes - contains the country ID and country name 
- PISA weighted country-level means for math, reading, science and socio-economic status
- PISA weighted proportions rolled up to country-level from the student and well-being questionnaires 
- World Bank data for country-level gross domestic product (GDP)
- UNESCO data for country-level percent of gross domestic product spent on education

**Output**: dfCOG.csv  
**Program History/Modifications**:<br>
03/17/2025    Initial Version

In [1]:
import pandas as pd
#pip install pyreadstat
import pyreadstat

## PISA Data

In [2]:
#NOTE:
#Tried reading from Github, but blocked due to consent issues because the PISA data,
#which required that we make the Github site private. Specifically, we got a 404 error due to permissions.
#As such we have saved the data on our local machines.

#Read in country names and codes
PISA_Country_Codes = pd.read_excel("PISA_Country_Codes.xlsx")
PISA_Country_Codes.head()

   CNTRYID         country
0      100        Bulgaria
1      116        Cambodia
2      124          Canada
3      152           Chile
4      158  Chinese Taipei

In [3]:
PISA_Country_Codes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CNTRYID  81 non-null     int64
 1   country  81 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.4+ KB

In [4]:
#Read in country-level reading scores
PISA_Country_Math = pd.read_excel("PISA Country_level_data_mathematics.xlsx")
PISA_Country_Math = PISA_Country_Math.filter(regex='country|_mean|diff')
PISA_Country_Math.head()

,country,math_all_mean,math_10th_mean,math_25th_mean,math_50th_mean,math_75th_mean,math_90th_mean,math_diff_90_10,math_diff_90_10_se
0,OECD average,472,355,408,472,535,590,235,0.7
1,Australia,487,358,416,485,556,619,261,3.4
2,Austria,487,362,420,489,554,608,246,4.1
3,Belgium,489,359,420,492,559,614,254,3.6
4,Canada,497,375,430,496,562,619,244,2.7

In [5]:
#Read in country-level reading scores
PISA_Country_Read = pd.read_excel("PISA Country_level_data_reading.xlsx")
PISA_Country_Read = PISA_Country_Read.filter(regex='country|_mean|diff')
PISA_Country_Read.head()

,country,read_all_mean,read_10th_mean,read_25th_mean,read_50th_mean,read_75th_mean,read_90th_mean,read_diff_90_10,read_diff_90_10_se
0,OECD average,476,342,406,479,547,603,262,0.8
1,Australia,498,351,422,502,576,638,288,3.6
2,Austria,480,340,406,485,557,613,273,4.9
3,Belgium,479,337,407,484,555,610,274,4.6
4,Canada,507,365,434,511,583,643,278,3.8

In [6]:
#Read in country-level science scores
PISA_Country_Scie = pd.read_excel("PISA Country_level_data_science.xlsx")
PISA_Country_Scie = PISA_Country_Scie.filter(regex='country|_mean|diff')
PISA_Country_Scie.head()

,country,scie_all_mean,scie_10th_mean,scie_25th_mean,scie_50th_mean,scie_75th_mean,scie_90th_mean,scie_diff_90_10,scie_diff_90_10_se
0,OECD average,485,356,416,486,554,611,254,0.8
1,Australia,507,364,430,508,583,647,283,3.9
2,Austria,491,356,418,495,565,622,266,4.1
3,Belgium,491,352,419,496,564,618,266,4.4
4,Canada,515,383,446,516,584,643,260,3.4

In [7]:
#Read in country-level reading scores
PISA_Country_Math_Sex = pd.read_excel("PISA Country_level_data_math_sex.xlsx")
PISA_Country_Math_Sex = PISA_Country_Math_Sex.filter(regex='country|_mean|diff')
PISA_Country_Math_Sex.head()

,country,math_female_all_mean,math_female_10th_mean,math_female_50th_mean,math_female_90th_mean,math_male_all_mean,math_male_10th_mean,math_male_50th_mean,math_male_90th_mean,math_diffsex_all_mean,math_diffsex_all_se
0,OECD average,468,357,467,579,477,353,477,600,9,0.5
1,Australia,481,361,478,605,493,356,491,631,11,3.0
2,Austria,478,358,479,593,497,366,499,621,19,3.0
3,Belgium,486,359,489,605,493,360,496,623,8,4.1
4,Canada,491,377,490,606,503,373,504,631,12,1.7

In [8]:
#Read in country-level reading scores
PISA_Country_SES = pd.read_excel("PISA Country_level_data_ses.xlsx")
PISA_Country_SES = PISA_Country_SES.filter(regex='country|_mean|diff')
PISA_Country_SES.head() 
#SES file does not have data for Costa Rica

,country,ses_all_mean,ses_bottom_quarter_mean,ses_second_quarter_mean,ses_third_quarter_mean,ses_fourth_quarter_mean,ses_top_minus_bottom_mean,ses_10th_mean,ses_90th_mean,ses_diff_90_10,ses_diff_90_10_se
0,OECD average,0.00,-1.22,-0.26,0.41,1.09,2.31,-1.23,1.12,2.34,0.01
1,Australia,0.38,-0.80,0.21,0.80,1.31,2.10,-0.80,1.31,2.11,0.01
2,Austria,0.07,-1.18,-0.21,0.47,1.2,2.37,-1.15,1.23,2.38,0.03
3,Belgium,0.08,-1.19,-0.15,0.53,1.14,2.33,-1.17,1.16,2.34,0.03
4,Canada,0.38,-0.66,0.19,0.74,1.25,1.91,-0.68,1.26,1.94,0.02

In [9]:
#Read in country-level weighted proportions as rolled up from the student data
#keep the proportion variables and the country ID for merging
PISA_Country_Proportions = pd.read_csv("Weighted_Counts_and_Proportions_All.csv")
PISA_Country_Proportions = PISA_Country_Proportions.filter(regex='CNTRYID|_proportion')
PISA_Country_Proportions.head()

,CNTRYID,ST307Q02JA_1.0_proportion,ST307Q02JA_2.0_proportion,ST307Q02JA_3.0_proportion,ST307Q02JA_4.0_proportion,ST307Q02JA_5.0_proportion,ST301Q10JA_1.0_proportion,ST301Q10JA_2.0_proportion,ST301Q10JA_3.0_proportion,ST301Q10JA_4.0_proportion,...,WB154Q09HA_5.0_proportion,ST258Q01JA_1.0_proportion,ST258Q01JA_2.0_proportion,ST258Q01JA_3.0_proportion,ST258Q01JA_4.0_proportion,ST258Q01JA_5.0_proportion,ST062Q01TA_1.0_proportion,ST062Q01TA_2.0_proportion,ST062Q01TA_3.0_proportion,ST062Q01TA_4.0_proportion
0,8,0.1069,0.0729,0.1089,0.4258,0.2855,0.0575,0.0362,0.0874,0.3880,...,NaN,0.7492,0.0545,0.0383,0.0234,0.1347,0.6029,0.2982,0.0540,0.0449
1,31,0.1383,0.0861,0.1838,0.3727,0.2190,0.0923,0.0393,0.1199,0.3924,...,NaN,0.6117,0.1087,0.0736,0.0320,0.1739,0.5702,0.2966,0.0723,0.0609
2,32,0.1037,0.1110,0.2095,0.3820,0.1938,0.0453,0.0334,0.1548,0.4982,...,NaN,NaN,NaN,NaN,NaN,NaN,0.8529,0.1128,0.0153,0.0190
3,36,0.0310,0.0972,0.2671,0.4752,0.1297,0.0169,0.0371,0.2709,0.4986,...,NaN,NaN,NaN,NaN,NaN,NaN,0.5703,0.3142,0.0622,0.0533
4,40,0.0422,0.0953,0.1145,0.4507,0.2973,0.0414,0.0771,0.1949,0.4263,...,NaN,NaN,NaN,NaN,NaN,NaN,0.8710,0.0912,0.0134,0.0244

## GDP by Country

In [10]:
#Read in country-level GDP
Country_GDP = pd.read_csv("gdp-per-capita-worldbank.csv")
Country_GDP.rename(columns = {'Entity': 'country'}, inplace = True)
Country_GDP.rename(columns = {'GDP per capita, PPP (constant 2021 international $)': 'country_gdp'}, inplace = True)
Country_GDP_2021 = Country_GDP[Country_GDP['Year'] == 2021]
Country_GDP_2021=Country_GDP_2021.drop(["Year", "Code"], axis = 1)
Country_GDP_2021.head()

         country  country_gdp
21   Afghanistan    2144.1665
55       Albania   16353.8090
89       Algeria   14496.8650
123      Andorra   59332.2030
157       Angola    7408.1265

In [11]:
#Fix the country names on the GDP file to match the PISA file
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Azerbaijan', 'Baku (Azerbaijan)')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Brunei', 'Brunei Darussalam')

# 'Chinese Taipei' / Taiwan not on the GDP file

Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Czechia', 'Czech Republic')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Hong Kong', 'Hong Kong (China)')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('South Korea', 'Korea')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Macao', 'Macao (China)')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Palestine', 'Palestinian  Authority')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Slovakia', 'Slovak Republic')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Turkey', 'Türkiye')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Ukraine', 'Ukrainian regions (18 of 27)')
Country_GDP_2021['country'] = Country_GDP_2021['country'].replace('Vietnam', 'Viet Nam')

In [12]:
Country_GDP_2021.describe()

         country_gdp
count     213.000000
mean    25822.604541
std     25794.941595
min       836.665600
25%      6214.017000
50%     16353.809000
75%     38862.090000
max    137947.340000

## GDP Spending on Education

In [13]:
#Read in country-level percent of GDP spending on education. Take the most recent data from 2019-2022
Country_GDP_Ed = pd.read_csv("UNESCO_Percent_GDP_Education.csv")
Country_GDP_Ed.rename(columns = {'Country Name': 'country'}, inplace = True)
Country_GDP_Ed = Country_GDP_Ed.drop(Country_GDP_Ed.columns[4:63],axis = 1)
Country_GDP_Ed.head()

,country,Country Code,Indicator Name,Indicator Code,2019,2020,2021,2022,2023
0,Aruba,ABW,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,4.435043,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,4.944317,4.352440,4.771326,4.628624,NaN
2,Afghanistan,AFG,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,3.047400,3.398741,3.203484,2.905294,NaN
4,Angola,AGO,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,2.073064,2.667447,2.297109,2.332126,NaN

In [14]:
#coalesce values in specific column order
Country_GDP_Ed['ed_percent_gdp'] = Country_GDP_Ed[['2023', '2022', '2021','2020','2019']].bfill(axis=1).iloc[:, 0]
Country_GDP_Ed.head()

,country,Country Code,Indicator Name,Indicator Code,2019,2020,2021,2022,2023,ed_percent_gdp
0,Aruba,ABW,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,4.435043,NaN,NaN,NaN,NaN,4.435043
1,Africa Eastern and Southern,AFE,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,4.944317,4.352440,4.771326,4.628624,NaN,4.628624
2,Afghanistan,AFG,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,3.047400,3.398741,3.203484,2.905294,NaN,2.905294
4,Angola,AGO,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,2.073064,2.667447,2.297109,2.332126,NaN,2.332126

In [15]:
Country_GDP_Ed = Country_GDP_Ed.drop(['2023', '2022', '2021','2020','2019', 'Country Code', 'Indicator Name', 'Indicator Code'],axis = 1)

In [16]:
#Fix the country names on the GDP file to match the PISA file
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Azerbaijan', 'Baku (Azerbaijan)')

# 'Chinese Taipei' / Taiwan not on the GDP ED file
          
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Czechia', 'Czech Republic')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Hong Kong SAR, China', 'Hong Kong (China)')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Korea, Rep.', 'Korea')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Macao SAR, China', 'Macao (China)')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('West Bank and Gaza', 'Palestinian  Authority')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Turkiye', 'Türkiye')
Country_GDP_Ed['country'] = Country_GDP_Ed['country'].replace('Ukraine', 'Ukrainian regions (18 of 27)')

#The following countries are missing the percentage of GDP spent on education: Brunei Darussalam, 
#Colombia, Kosovo, Montenegro, and North Macedonia

Country_GDP_Ed.head()

                       country  ed_percent_gdp
0                        Aruba        4.435043
1  Africa Eastern and Southern        4.628624
2                  Afghanistan             NaN
3   Africa Western and Central        2.905294
4                       Angola        2.332126

## Merge Data Files

In [17]:
# Merge files with country name in commong including Math, Reading, Science, Math & Sex, SES, GDP, %GDP for ED
dfCOG = pd.merge(PISA_Country_Codes, PISA_Country_Math, how = 'left', on = 'country')
dfCOG = pd.merge(dfCOG, PISA_Country_Read, how = 'left',  on = 'country')
dfCOG = pd.merge(dfCOG, PISA_Country_Scie, how = 'left',  on = 'country')
dfCOG = pd.merge(dfCOG, PISA_Country_Math_Sex, how = 'left',  on = 'country')
dfCOG = pd.merge(dfCOG, PISA_Country_SES, how = 'left',  on = 'country')
dfCOG = pd.merge(dfCOG, Country_GDP_2021, how = 'left',  on = 'country')
dfCOG = pd.merge(dfCOG, Country_GDP_Ed, how = 'left',  on = 'country')
dfCOG.head()

,CNTRYID,country,math_all_mean,math_10th_mean,math_25th_mean,math_50th_mean,math_75th_mean,math_90th_mean,math_diff_90_10,math_diff_90_10_se,...,ses_second_quarter_mean,ses_third_quarter_mean,ses_fourth_quarter_mean,ses_top_minus_bottom_mean,ses_10th_mean,ses_90th_mean,ses_diff_90_10,ses_diff_90_10_se,country_gdp,ed_percent_gdp
0,100,Bulgaria,417,298,346,411,483,549,251,6.8,...,-0.61,0.21,0.96,2.61,-1.57,0.97,2.54,0.04,29536.6780,4.730330
1,116,Cambodia,336,244,288,336,383,428,184,4.6,...,-2.47,-1.66,-0.36,3.19,-3.61,-0.27,3.34,0.07,6225.5327,2.951152
2,124,Canada,497,375,430,496,562,619,244,2.7,...,0.19,0.74,1.25,1.91,-0.68,1.26,1.94,0.02,55781.7000,4.139572
3,152,Chile,412,315,358,409,464,514,198,3.3,...,-0.85,-0.18,0.7,2.41,-1.72,0.77,2.49,0.04,29105.1020,4.999240
4,158,Chinese Taipei,547,393,470,554,628,687,294,6.8,...,-0.47,0.19,0.91,2.28,-1.39,0.94,2.34,0.03,NaN,NaN

In [18]:
#Merge the proportions which were rolled up from the student data
dfCOG = pd.merge(dfCOG, PISA_Country_Proportions, how = 'left',  on = 'CNTRYID')
dfCOG.head()

,CNTRYID,country,math_all_mean,math_10th_mean,math_25th_mean,math_50th_mean,math_75th_mean,math_90th_mean,math_diff_90_10,math_diff_90_10_se,...,WB154Q09HA_5.0_proportion,ST258Q01JA_1.0_proportion,ST258Q01JA_2.0_proportion,ST258Q01JA_3.0_proportion,ST258Q01JA_4.0_proportion,ST258Q01JA_5.0_proportion,ST062Q01TA_1.0_proportion,ST062Q01TA_2.0_proportion,ST062Q01TA_3.0_proportion,ST062Q01TA_4.0_proportion
0,100,Bulgaria,417,298,346,411,483,549,251,6.8,...,NaN,0.7780,0.0500,0.0336,0.0164,0.1221,0.8813,0.0781,0.0181,0.0225
1,116,Cambodia,336,244,288,336,383,428,184,4.6,...,NaN,0.3225,0.2248,0.1615,0.0685,0.2227,0.9075,0.0742,0.0091,0.0093
2,124,Canada,497,375,430,496,562,619,244,2.7,...,NaN,0.9139,0.0278,0.0127,0.0049,0.0408,0.7139,0.2099,0.0434,0.0328
3,152,Chile,412,315,358,409,464,514,198,3.3,...,NaN,0.8692,0.0484,0.0133,0.0065,0.0625,0.9431,0.0437,0.0069,0.0063
4,158,Chinese Taipei,547,393,470,554,628,687,294,6.8,...,NaN,0.9028,0.0506,0.0235,0.0064,0.0168,0.9759,0.0141,0.0048,0.0053

In [19]:
dfCOG.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Columns: 113 entries, CNTRYID to ST062Q01TA_4.0_proportion
dtypes: float64(79), int64(31), object(3)
memory usage: 71.6+ KB

## Missing Data

In [20]:
#Check country missing socioeconomic status
missing_SES = dfCOG[dfCOG['ses_all_mean'].isnull()]
missing_SES.value_counts('country')

country
Costa Rica    1
Name: count, dtype: int64

In [21]:
#Check country missing GDP
missing_GDP = dfCOG[dfCOG['country_gdp'].isnull()]
missing_GDP.value_counts('country')

country
Chinese Taipei    1
Name: count, dtype: int64

In [22]:
#Check countries not missing well being questions
not_missing_WB = dfCOG[dfCOG['WB154Q09HA_5.0_proportion'].notnull()]
not_missing_WB.value_counts('country')

country
Brazil                  1
Costa Rica              1
Hong Kong (China)       1
Hungary                 1
Ireland                 1
Macao (China)           1
Mexico                  1
Netherlands             1
New Zealand             1
Panama                  1
Saudi Arabia            1
Slovenia                1
Spain                   1
United Arab Emirates    1
Name: count, dtype: int64

In [23]:
#Check country missing GDP percent spent on education
missing_GDP_Ed = dfCOG[dfCOG['ed_percent_gdp'].isnull()]
missing_GDP_Ed.value_counts('country')

country
Brunei Darussalam    1
Chinese Taipei       1
Colombia             1
Kosovo               1
Montenegro           1
North Macedonia      1
Name: count, dtype: int64

In [24]:
#Check the distribution of ed_percent_gdp
dfCOG['ed_percent_gdp'].describe()

count    75.000000
mean      4.501615
std       1.200213
min       1.275171
25%       3.625471
50%       4.615470
75%       5.279822
max       7.572200
Name: ed_percent_gdp, dtype: float64

In [25]:
#Replace the missing ed_percent_gdp with the median
median_val = dfCOG['ed_percent_gdp'].median()
if ([dfCOG['country'] != 'Chinese Taipei']):
    dfCOG['ed_percent_gdp'] = dfCOG['ed_percent_gdp'].fillna(median_val)
dfCOG['ed_percent_gdp'].describe()

count    81.000000
mean      4.510049
std       1.154718
min       1.275171
25%       3.738610
50%       4.615470
75%       5.235860
max       7.572200
Name: ed_percent_gdp, dtype: float64

In [26]:
#Check country missing GDP percent spent on education
missing_GDP_Ed2 = dfCOG[dfCOG['ed_percent_gdp'].isnull()]
missing_GDP_Ed2.value_counts('country')

Series([], Name: count, dtype: int64)

## Add Constructed Variables for the Analysis

In [27]:
def get_region(country):
    # Western Europe countries
    western_europe = [
        'Belgium', 'Denmark', 'France', 'Germany', 'Iceland', 'Ireland', 'Italy', 'Kosovo',
        'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Monaco', 'Netherlands', 'Norway',
        'Poland', 'Portugal', 'Romania', 'Spain', 'Sweden', 'Switzerland', 'United Kingdom', 'Morocco','Finland'
    ]

    # Eastern Europe countries
    eastern_europe = [
        'Albania', 'Armenia', 'Austria', 'Bulgaria', 'Croatia', 'Czech Republic', 'Estonia',
        'Georgia', 'Hungary', 'Kazakhstan', 'Moldova', 'Montenegro', 'North Macedonia', 'Poland',
        'Serbia', 'Slovak Republic', 'Slovenia', 'Ukrainian regions (18 of 27)','Greece'
    ]

    # North America countries
    north_america = ['Canada', 'United States', 'Mexico', 'Costa Rica', 'Panama',
                     'Dominican Republic', 'Guatemala', 'El Salvador','Jamaica']

    # South America countries
    south_america = ['Argentina', 'Chile', 'Colombia', 'Paraguay', 'Peru', 'Brazil', 'Uruguay']

    # Asia countries
    asia = ['Cambodia', 'Chinese Taipei', 'Hong Kong (China)', 'Indonesia', 'Israel', 'Japan',
            'Kazakhstan', 'Korea', 'Malaysia', 'Macao (China)', 'Mongolia', 'Philippines', 'Qatar',
            'Saudi Arabia', 'Singapore', 'Thailand', 'Viet Nam', 'Uzbekistan', 'Brunei Darussalam','Australia', 'New Zealand']

    # Middle East countries
    middle_east = ['Jordan', 'United Arab Emirates', 'Palestinian  Authority','Türkiye','Baku (Azerbaijan)','Cyprus']

    # Check which region the country belongs to
    if country in western_europe:
        return 'Western Europe'
    elif country in eastern_europe:
        return 'Eastern Europe'
    elif country in north_america:
        return 'North America'
    elif country in south_america:
        return 'South America'
    elif country in asia:
        return 'Asia'
    elif country in middle_east:
        return 'Middle East'
    else:
        return 'Unknown'

# Add the 'Region' column to the DataFrame
dfCOG['Geo_Region'] = dfCOG['country'].apply(get_region)

In [28]:
dfCOG['Geo_Region'].value_counts()

Geo_Region
Western Europe    22
Asia              20
Eastern Europe    17
North America      9
South America      7
Middle East        6
Name: count, dtype: int64

In [29]:
#Check the mean math scores of the counties included in the PISA
dfCOG['math_all_mean'].describe()
#PISA defines minimum proficiency as Level 2. For Math this is a score of 420.07 or more.

count     81.000000
mean     437.654321
std       58.190884
min      336.000000
25%      389.000000
50%      441.000000
75%      483.000000
max      575.000000
Name: math_all_mean, dtype: float64

In [30]:
#Check the mean reading scores of the counties included in the PISA
dfCOG['read_all_mean'].describe()
#PISA defines minimum proficiency as Level 2. For reading this is a score of 407.47 or more.

count     81.000000
mean     435.024691
std       56.120178
min      329.000000
25%      386.000000
50%      438.000000
75%      480.000000
max      543.000000
Name: read_all_mean, dtype: float64

In [31]:
#Check the mean science scores of the counties included in the PISA
dfCOG['scie_all_mean'].describe()
#PISA defines minimum proficiency as Level 2. For science this is a score of 409.54 or more.

count     81.000000
mean     446.864198
std       55.737724
min      347.000000
25%      403.000000
50%      447.000000
75%      494.000000
max      561.000000
Name: scie_all_mean, dtype: float64

In [32]:
#Add constructed variables for minimum proficiency
#Average test score for the country below the minimal standards for proficiency
#Math = <420.07, greater than or equal to 420.07 
math_bins = [0, 420.07, 600]
#Reading = <407.47, greater than or equal to 407.47 
read_bins = [0, 407.47, 600]
#Science = <409.54, greater than or equal to 409.54
scie_bins = [0, 409.54, 600]
#Variable labels
proficiency_labels = ['Below minimum proficiency', 'Met minimum proficiency']
#Create variables 
dfCOG['math_min_proficiency'] = pd.cut(dfCOG['math_all_mean'], bins=math_bins, labels=proficiency_labels, right=True)
dfCOG['read_min_proficiency'] = pd.cut(dfCOG['read_all_mean'], bins=read_bins, labels=proficiency_labels, right=True)
dfCOG['scie_min_proficiency'] = pd.cut(dfCOG['scie_all_mean'], bins=scie_bins, labels=proficiency_labels, right=True)

In [33]:
#Check variable creation - math minimal proficiency
print(dfCOG[['math_all_mean','math_min_proficiency']])

    math_all_mean       math_min_proficiency
0             417  Below minimum proficiency
1             336  Below minimum proficiency
2             497    Met minimum proficiency
3             412  Below minimum proficiency
4             547    Met minimum proficiency
..            ...                        ...
76            465    Met minimum proficiency
77            409  Below minimum proficiency
78            364  Below minimum proficiency
79            441    Met minimum proficiency
80            442    Met minimum proficiency

[81 rows x 2 columns]

In [34]:
#Check variable creation - reading minimal proficiency
print(dfCOG[['read_all_mean','read_min_proficiency']])

    read_all_mean       read_min_proficiency
0             404  Below minimum proficiency
1             329  Below minimum proficiency
2             507    Met minimum proficiency
3             448    Met minimum proficiency
4             515    Met minimum proficiency
..            ...                        ...
76            504    Met minimum proficiency
77            430    Met minimum proficiency
78            336  Below minimum proficiency
79            428    Met minimum proficiency
80            429    Met minimum proficiency

[81 rows x 2 columns]

In [35]:
#Check variable creation - science minimal proficiency
print(dfCOG[['scie_all_mean','scie_min_proficiency']])

    scie_all_mean       scie_min_proficiency
0             421    Met minimum proficiency
1             347  Below minimum proficiency
2             515    Met minimum proficiency
3             444    Met minimum proficiency
4             537    Met minimum proficiency
..            ...                        ...
76            499    Met minimum proficiency
77            435    Met minimum proficiency
78            355  Below minimum proficiency
79            450    Met minimum proficiency
80            446    Met minimum proficiency

[81 rows x 2 columns]

In [36]:
#Check the GDP of the counties included in the PISA
dfCOG['country_gdp'].describe()
#The World Bank defines low-income countries as <1.085, lower-middle income as 1,046-4,095, 
#upper-middle income as 4,096 - 12,695 and High-income as >12,695. As such, we only have
#upper-middle income and high-income countries in the sample included in PISA.

count        80.000000
mean      40573.125979
std       26573.328769
min        5663.121600
25%       18705.666750
50%       37492.644500
75%       56166.665500
max      131864.100000
Name: country_gdp, dtype: float64

In [37]:
#Add constructed variables
#Income grouping according to world bank
gdp_bins = [4095, 12695, 131864]
gdp_labels = ['<=12,695 Upper-Middle Income', '>12,695 High Income']
dfCOG['country_gdp_cat'] = pd.cut(dfCOG['country_gdp'], bins=gdp_bins, labels=gdp_labels, right=True)

In [38]:
#Check variable creation - income
print(dfCOG[['country_gdp_cat','country_gdp']])

                 country_gdp_cat  country_gdp
0            >12,695 High Income   29536.6780
1   <=12,695 Upper-Middle Income    6225.5327
2            >12,695 High Income   55781.7000
3            >12,695 High Income   29105.1020
4                            NaN          NaN
..                           ...          ...
76           >12,695 High Income   71318.3050
77           >12,695 High Income   29441.4770
78  <=12,695 Upper-Middle Income    9247.6440
79           >12,695 High Income   17846.4080
80           >12,695 High Income   78248.8000

[81 rows x 2 columns]

In [39]:
twenty_five_bins = [0, 0.25, 1]
twenty_five_labels = ['<25%', '>=25%']
fifty_bins = [0, 0.5, 1]
fifty_labels = ['<50%', '>=50%']
sixty_bins = [0, 0.60, 1]
sixty_labels = ['<60%', '>=60%']
seventy_five_bins = [0, 0.75, 1]
seventy_five_labels = ['<75%', '>=75%']

thirds_bins = [0, 0.33, 0.66, 1]
thirds_labels = ['Bottom third', 'Middle third', 'Top third']
fourths_bins = [0, 0.25, 0.5, 0.75, 1]
fourths_labels = ['0-24%', '25-49%', '50-74%', '75-100%']

low_thirds_bins = [0, 0.1, 0.2, 0.3]
low_thirds_labels = ['0-9%', '10-19%', '20-30%']

In [40]:
#Add variable for satisfaction level with life
# Satisfaction level: proportion 8-10
dfCOG['high_life_satisfaction'] = dfCOG['ST016Q01NA_8.0_proportion'] + dfCOG['ST016Q01NA_9.0_proportion'] + dfCOG['ST016Q01NA_10.0_proportion']
#Grouping highly statisfied
dfCOG['high_life_satisfaction_cat'] = pd.cut(dfCOG['high_life_satisfaction'], bins=fifty_bins, labels=fifty_labels, right=True)

In [41]:
#Check variable creation - high life satisfaction
print(dfCOG[['high_life_satisfaction_cat','high_life_satisfaction','ST016Q01NA_8.0_proportion','ST016Q01NA_9.0_proportion','ST016Q01NA_10.0_proportion']])

   high_life_satisfaction_cat  high_life_satisfaction  \
0                       >=50%                  0.5293
1                       >=50%                  0.5879
2                         NaN                     NaN
3                        <50%                  0.3990
4                        <50%                  0.4272
..                        ...                     ...
76                        NaN                     NaN
77                      >=50%                  0.5074
78                      >=50%                  0.7233
79                      >=50%                  0.5541
80                       <50%                  0.2697

    ST016Q01NA_8.0_proportion  ST016Q01NA_9.0_proportion  \
0                      0.1293                     0.1102
1                      0.1381                     0.1041
2                         NaN                        NaN
3                      0.1551                     0.1143
4                      0.1896                     0.1111
..                        ...                        ...
76                        NaN                        NaN
77                     0.1912                     0.1435
78                     0.0974                     0.1031
79                     0.1761                     0.1442
80                     0.1339                     0.0645

    ST016Q01NA_10.0_proportion
0                       0.2898
1                       0.3457
2                          NaN
3                       0.1296
4                       0.1265
..                         ...
76                         NaN
77                      0.1727
78                      0.5228
79                      0.2338
80                      0.0713

[81 rows x 5 columns]

In [42]:
dfCOG['ST263Q02JA_1.0_proportion'].describe()

count    75.000000
mean      0.147184
std       0.045934
min       0.073000
25%       0.114850
50%       0.136500
75%       0.175600
max       0.286500
Name: ST263Q02JA_1.0_proportion, dtype: float64

In [43]:
#Add variables for Growth Mindset
#Strongly disagree with intelligence is something that cannot change
high_growth_bins = [0, 0.1, 0.2, 0.3]
high_growth_labels = ['Low', 'Medium', 'High']
dfCOG['high_growth_mindset_cat'] = pd.cut(dfCOG['ST263Q02JA_1.0_proportion'], bins=high_growth_bins, labels=high_growth_labels, right=True)

In [44]:
#Strongly agree with intelligence is something that cannot change
low_growth_bins = [0, 0.07, 0.14, 0.25]
low_growth_labels = ['Low', 'Medium', 'High']
dfCOG['low_growth_mindset_cat'] = pd.cut(dfCOG['ST263Q02JA_4.0_proportion'], bins=low_growth_bins, labels=low_growth_labels, right=True)

In [45]:
#Check variable creation - high growth mindset
print(dfCOG[['high_growth_mindset_cat','ST263Q02JA_1.0_proportion']])

   high_growth_mindset_cat  ST263Q02JA_1.0_proportion
0                     High                     0.2248
1                      NaN                        NaN
2                   Medium                     0.1666
3                     High                     0.2324
4                   Medium                     0.1281
..                     ...                        ...
76                    High                     0.2241
77                  Medium                     0.1375
78                    High                     0.2156
79                  Medium                     0.1996
80                  Medium                     0.1154

[81 rows x 2 columns]

In [46]:
#Check variable creation - high growth mindset
print(dfCOG[['low_growth_mindset_cat','ST263Q02JA_4.0_proportion']])

   low_growth_mindset_cat  ST263Q02JA_4.0_proportion
0                  Medium                     0.1017
1                     NaN                        NaN
2                  Medium                     0.0711
3                  Medium                     0.0839
4                  Medium                     0.0854
..                    ...                        ...
76                    Low                     0.0639
77                 Medium                     0.0746
78                 Medium                     0.1235
79                 Medium                     0.0760
80                 Medium                     0.0878

[81 rows x 2 columns]

In [47]:
dfCOG['high_growth_mindset_cat'].value_counts()

high_growth_mindset_cat
Medium    55
Low       10
High      10
Name: count, dtype: int64

In [48]:
dfCOG['low_growth_mindset_cat'].value_counts()

low_growth_mindset_cat
Medium    49
Low       15
High      11
Name: count, dtype: int64

In [49]:
#Add variables for Grit
dfCOG['high_grit'] = dfCOG['ST307Q02JA_4.0_proportion']+dfCOG['ST307Q02JA_5.0_proportion']
#Grouping high grit
dfCOG['high_grit_cat'] = pd.cut(dfCOG['high_grit'], bins=sixty_bins, labels=sixty_labels, right=True)

In [50]:
dfCOG['low_grit'] = dfCOG['ST307Q02JA_1.0_proportion']+dfCOG['ST307Q02JA_2.0_proportion']
#Grouping low grit
dfCOG['low_grit_cat'] = pd.cut(dfCOG['low_grit'], bins=low_thirds_bins, labels=low_thirds_labels, right=True)

In [51]:
dfCOG['high_grit'].describe()

count    72.000000
mean      0.639626
std       0.083764
min       0.375100
25%       0.583450
50%       0.649300
75%       0.702700
max       0.796700
Name: high_grit, dtype: float64

In [52]:
dfCOG['low_grit'].describe()

count    72.000000
mean      0.159558
std       0.048554
min       0.050300
25%       0.125850
50%       0.151500
75%       0.191725
max       0.288600
Name: low_grit, dtype: float64

In [53]:
#Check variable creation - high grit
print(dfCOG[['high_grit_cat','high_grit','ST307Q02JA_4.0_proportion', 'ST307Q02JA_5.0_proportion']])

   high_grit_cat  high_grit  ST307Q02JA_4.0_proportion  \
0          >=60%     0.6108                     0.4763
1            NaN        NaN                        NaN
2          >=60%     0.6175                     0.4339
3          >=60%     0.7616                     0.4511
4          >=60%     0.7018                     0.4713
..           ...        ...                        ...
76           NaN        NaN                        NaN
77         >=60%     0.7166                     0.4914
78         >=60%     0.6906                     0.5263
79          <60%     0.5973                     0.4314
80          <60%     0.5996                     0.4496

    ST307Q02JA_5.0_proportion
0                      0.1345
1                         NaN
2                      0.1836
3                      0.3105
4                      0.2305
..                        ...
76                        NaN
77                     0.2252
78                     0.1643
79                     0.1659
80                     0.1500

[81 rows x 4 columns]

In [54]:
dfCOG['high_grit_cat'].value_counts()

high_grit_cat
>=60%    49
<60%     23
Name: count, dtype: int64

In [55]:
dfCOG['low_grit_cat'].value_counts()

low_grit_cat
10-19%    49
20-30%    16
0-9%       7
Name: count, dtype: int64

In [56]:
#Add variables for love of learning
dfCOG['high_love_learn'] = dfCOG['ST301Q10JA_4.0_proportion']+dfCOG['ST301Q10JA_5.0_proportion']
#Grouping high love of learning
dfCOG['high_love_learn_cat'] = pd.cut(dfCOG['high_love_learn'], bins=seventy_five_bins, labels=seventy_five_labels, right=True)

In [57]:
dfCOG['high_love_learn'].describe()

count    76.000000
mean      0.746396
std       0.092314
min       0.550200
25%       0.672275
50%       0.755650
75%       0.824775
max       0.903500
Name: high_love_learn, dtype: float64

In [58]:
dfCOG['high_love_learn_cat'].value_counts()

high_love_learn_cat
<75%     38
>=75%    38
Name: count, dtype: int64

In [59]:
dfCOG.to_csv("dfCOG.csv")